'use client';

import React, { useState } from 'react';
import { useErp } from '../../../context/ErpContext';
import { erpService } from '../../../services/erpService';
import { EWayBill } from '../../../types/erp';
import { formatDate } from '../../../utils/dateUtils';
import DataTable from '../../../components/shared/DataTable';
import IndianDateInput from '../../../components/shared/IndianDateInput';
import { FileText, Plus, CheckCircle, Clock, Download } from 'lucide-react';

export default function EWayBillsPage() {
  const { db, refreshDb, showToast } = useErp();
  const [selectedEWB, setSelectedEWB] = useState<any>(null);
  const [isCreateOpen, setIsCreateOpen] = useState(false);

  // Form states
  const [invoiceId, setInvoiceId] = useState('');
  const [selectedVehicleId, setSelectedVehicleId] = useState('');
  const [transporterName, setTransporterName] = useState('BrijRani Logistics');
  const [mode, setMode] = useState<'Road' | 'Rail' | 'Air' | 'Ship'>('Road');
  const [distance, setDistance] = useState(350);
  const [validFrom, setValidFrom] = useState(new Date().toISOString().split('T')[0]);
  const [validUntil, setValidUntil] = useState(new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]);

  const invoices = db.salesInvoices;
  const customers = db.customers;
  const vehicles = db.vehicles;

  const handleAction = (act: string) => {
    showToast(`Request sent to National Informatics Centre (NIC) portal: ${act}`, 'info');
  };

  const handleCreateEWB = (e: React.FormEvent) => {
    e.preventDefault();
    if (!invoiceId || !selectedVehicleId) {
      showToast('Please fill all mandatory fields', 'error');
      return;
    }

    const selectedInv = invoices.find(inv => inv.id === invoiceId);
    if (!selectedInv) return;

    const selectedVeh = vehicles.find(v => v.id === selectedVehicleId);
    if (!selectedVeh) return;

    const ewayBillNo = String(Math.floor(100000000000 + Math.random() * 900000000000));
    const id = `EWB-${Date.now()}`;

    const newEWB: EWayBill = {
      id,
      ewayBillNo,
      invoiceNo: selectedInv.invoiceNo,
      customerId: selectedInv.customerId,
      partyName: customers.find(c => c.id === selectedInv.customerId)?.name || 'Unknown Client',
      vehicleNo: selectedVeh.number,
      transporterName,
      mode,
      distance,
      validFrom,
      validUntil,
      status: 'Active'
    };

    erpService.ewayBills.create(newEWB);
    
    // Update invoice with E-Way Bill No
    selectedInv.ewayBillNo = ewayBillNo;
    erpService.salesInvoices.update(selectedInv);

    refreshDb();
    setIsCreateOpen(false);
    showToast(`E-Way Bill ${ewayBillNo} generated successfully via NIC API!`, 'success');
  };

  const printEWayBillPDF = (ewb: EWayBill) => {
    const html = `
      <html>
        <head>
          <title>EWayBill_${ewb.ewayBillNo}</title>
          <style>
            body { font-family: 'Courier New', Courier, monospace; color: #1e293b; padding: 30px; font-size: 12px; line-height: 1.4; }
            .border-box { border: 2px solid #000; padding: 15px; }
            .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 15px; }
            .gov-title { font-size: 16px; font-weight: bold; margin-bottom: 5px; }
            .subtitle { font-size: 13px; font-weight: bold; }
            .row { display: flex; justify-content: space-between; border-bottom: 1px dashed #cbd5e1; padding: 6px 0; }
            .col { flex: 1; }
            .bold { font-weight: bold; }
            .title-block { background: #f1f5f9; padding: 5px; font-weight: bold; text-transform: uppercase; border: 1px solid #000; margin: 15px 0 8px 0; }
            table { width: 100%; border-collapse: collapse; margin-top: 5px; margin-bottom: 15px; }
            th, td { border: 1px solid #000; padding: 6px; text-align: left; font-size: 11px; }
            th { background: #f8fafc; }
            .footer { text-align: center; margin-top: 30px; font-size: 10px; border-top: 1px solid #000; padding-top: 10px; }
            @media print {
              body { padding: 0; }
            }
          </style>
        </head>
        <body>
          <div class="border-box">
            <div class="header">
              <div class="gov-title">e-Way Bill System (Government of India)</div>
              <div class="subtitle">FORM GST EWB-01 (e-Way Bill)</div>
            </div>

            <div class="row">
              <div class="col"><span class="bold">e-Way Bill No:</span> ${ewb.ewayBillNo}</div>
              <div class="col" style="text-align: right;"><span class="bold">Generated Date:</span> ${ewb.validFrom} 10:15 AM</div>
            </div>
            <div class="row">
              <div class="col"><span class="bold">Generated By:</span> 10AABCB1234F1Z0 (BrijRani Agro Foods Ltd)</div>
              <div class="col" style="text-align: right;"><span class="bold">Status:</span> ${ewb.status.toUpperCase()}</div>
            </div>

            <div class="title-block">1. PART-A Details</div>
            
            <div class="row">
              <div class="col"><span class="bold">GSTIN of Supplier:</span> 10AABCB1234F1Z0</div>
              <div class="col"><span class="bold">Place of Dispatch:</span> Patna, Bihar</div>
            </div>
            <div class="row">
              <div class="col"><span class="bold">GSTIN of Recipient:</span> ${ewb.customerId ? '10XYZPD9876Q3Z1' : 'URP (Unregistered)'}</div>
              <div class="col"><span class="bold">Place of Delivery:</span> ${ewb.partyName}</div>
            </div>
            <div class="row">
              <div class="col"><span class="bold">Document No / Date:</span> ${ewb.invoiceNo} / ${ewb.validFrom}</div>
              <div class="col"><span class="bold">Transaction Type:</span> Outward Supply</div>
            </div>
            <div class="row">
              <div class="col"><span class="bold">HSN Code:</span> 1006 (Grains / Cereals)</div>
              <div class="col"><span class="bold">Distance (Kms):</span> ${ewb.distance} Kms</div>
            </div>

            <div class="title-block">2. PART-B Details (Vehicle & Transport)</div>
            
            <table>
              <thead>
                <tr>
                  <th>Mode of Transport</th>
                  <th>Vehicle Number</th>
                  <th>Transporter Doc No & Date</th>
                  <th>From (Transit point)</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>${ewb.mode}</td>
                  <td>${ewb.vehicleNo || 'N/A'}</td>
                  <td>${ewb.transporterName || 'BrijRani Logistics'}</td>
                  <td>Patna Gate Silo</td>
                </tr>
              </tbody>
            </table>

            <div class="row">
              <div class="col"><span class="bold">Validity From:</span> ${ewb.validFrom}</div>
              <div class="col" style="text-align: right;"><span class="bold">Validity Until:</span> ${ewb.validUntil}</div>
            </div>

            <div class="terms" style="margin-top: 30px; font-size: 11px;">
              <strong>Note:</strong> This is a computer-generated official e-Way Bill document issued under the provisions of Central Goods and Services Tax Rules, 2017. Carrier must present a print copy of this document during interstate road checkpoint inspection.
            </div>

            <div class="footer">
              National Informatics Centre (NIC) - Goods and Services Tax Portal
            </div>
          </div>

          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            }
          </script>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.open();
      printWindow.document.write(html);
      printWindow.document.close();
    }
  };

  const columns: any[] = [
    { header: 'E-Way Bill No', accessor: 'ewayBillNo', sortable: true },
    { header: 'Invoice Number', accessor: 'invoiceNo' },
    { header: 'Consignee Name', accessor: 'partyName' },
    { header: 'Vehicle Number', accessor: 'vehicleNo' },
    { header: 'Distance (Kms)', accessor: 'distance' },
    { header: 'Valid From', accessor: 'validFrom' },
    { header: 'Valid Until', accessor: 'validUntil' },
    { 
      header: 'Status', 
      accessor: (row: any) => (
        <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold border ${
          row.status === 'Active' ? 'bg-emerald-50 text-emerald-600 border-emerald-200' :
          row.status === 'Expired' ? 'bg-red-50 text-red-600 border-red-200 animate-pulse' :
          'bg-slate-50 text-slate-550 border-slate-200'
        }`}>
          {row.status}
        </span>
      )
    }
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-slate-800">E-Way Bills Register</h1>
          <p className="text-xs font-medium text-slate-400">Query government NIC e-way bills generated against inter-state sales dispatches.</p>
        </div>
        <button
          onClick={() => setIsCreateOpen(true)}
          className="flex items-center gap-1.5 px-3 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg font-bold text-xs cursor-pointer shadow-md shadow-primary-600/10 transition"
        >
          <Plus size={14} />
          <span>Generate E-Way Bill</span>
        </button>
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        <div className="xl:col-span-2">
          <DataTable
            data={db.ewayBills}
            columns={columns}
            searchPlaceholder="Search e-way bill number..."
            searchField="ewayBillNo"
            onRowClick={(row) => setSelectedEWB(row)}
            exportFileName="eway_bills_registry"
          />
        </div>

        {/* Selected details panel */}
        <div>
          {selectedEWB ? (
            <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm space-y-5">
              <div className="border-b border-slate-100 pb-4">
                <h3 className="text-sm font-bold text-slate-800">EWB: #{selectedEWB.ewayBillNo}</h3>
                <span className="text-[10px] text-slate-400 block mt-0.5">Invoice Ref: {selectedEWB.invoiceNo}</span>
              </div>

              <div className="space-y-2.5 text-xs font-semibold text-slate-655">
                <div className="flex justify-between border-b border-slate-50 pb-1.5">
                  <span className="text-slate-400">Transporter:</span>
                  <span>{selectedEWB.transporterName}</span>
                </div>
                <div className="flex justify-between border-b border-slate-50 pb-1.5">
                  <span className="text-slate-400">Transit Mode:</span>
                  <span>{selectedEWB.mode}</span>
                </div>
                <div className="flex justify-between border-b border-slate-50 pb-1.5">
                  <span className="text-slate-400">Distance Checked:</span>
                  <span>{selectedEWB.distance} Kms</span>
                </div>
                <div className="flex justify-between border-b border-slate-50 pb-1.5">
                  <span className="text-slate-400">Valid From:</span>
                  <span>{formatDate(selectedEWB.validFrom)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Valid Until:</span>
                  <span className={new Date(selectedEWB.validUntil) < new Date() ? 'text-red-655 font-bold' : ''}>
                    {formatDate(selectedEWB.validUntil)}
                  </span>
                </div>
              </div>

              {/* Action NIC buttons */}
              <div className="grid grid-cols-2 gap-2 pt-2">
                <button
                  onClick={() => handleAction('Update Vehicle Details')}
                  className="py-1.5 border border-slate-200 hover:border-slate-350 hover:bg-slate-50 text-slate-600 rounded-lg text-[10px] font-bold transition cursor-pointer"
                >
                  Update Vehicle
                </button>
                <button
                  onClick={() => handleAction('Extend Validity Period')}
                  className="py-1.5 border border-slate-200 hover:border-slate-350 hover:bg-slate-50 text-slate-600 rounded-lg text-[10px] font-bold transition cursor-pointer"
                >
                  Extend Validity
                </button>
                <button
                  onClick={() => printEWayBillPDF(selectedEWB)}
                  className="col-span-2 py-1.5 bg-slate-100 hover:bg-slate-200 border border-slate-200 text-slate-600 font-bold rounded-lg text-[10px] flex items-center justify-center gap-1.5 cursor-pointer transition"
                >
                  <Download size={12} className="text-red-500" />
                  <span>Download E-Way Bill PDF</span>
                </button>
              </div>
            </div>
          ) : (
            <div className="bg-slate-50 border border-dashed border-slate-300 rounded-xl p-8 text-center text-xs text-slate-400 font-semibold h-[250px] flex flex-col items-center justify-center gap-2">
              <FileText size={24} className="text-slate-300" />
              <span>Select an E-Way Bill row to view government portal details and perform updates.</span>
            </div>
          )}
        </div>
      </div>
      {/* Create Modal Drawer */}
      {isCreateOpen && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-[9999] flex items-center justify-center p-4">
          <div className="w-full max-w-xl bg-white border border-slate-200 rounded-xl shadow-2xl overflow-hidden animate-zoom-in">
            {/* Header */}
            <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-slate-50">
              <div>
                <h3 className="text-sm font-semibold text-slate-800">Generate Government E-Way Bill</h3>
                <p className="text-[10px] text-slate-400 mt-0.5">Generate compliance e-way bills against inter-state invoice dispatches.</p>
              </div>
              <button 
                onClick={() => setIsCreateOpen(false)}
                className="text-slate-400 hover:text-slate-600 font-bold"
              >
                &times;
              </button>
            </div>

            {/* Form */}
            <form onSubmit={handleCreateEWB} className="p-6 space-y-4 max-h-[75vh] overflow-y-auto">
              <div>
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Active Sales Invoice Reference *</label>
                <select
                  value={invoiceId}
                  onChange={e => setInvoiceId(e.target.value)}
                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white font-medium text-slate-700 focus:outline-none"
                  required
                >
                  <option value="">Select Sales Invoice</option>
                  {invoices.map(inv => (
                    <option key={inv.id} value={inv.id}>
                      {inv.invoiceNo} - {customers.find(c => c.id === inv.customerId)?.name || 'Unknown Customer'} (₹{inv.grandTotal.toLocaleString()})
                    </option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                {/* Vehicle Selection */}
                <div>
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Transport Vehicle Number *</label>
                  <select
                    value={selectedVehicleId}
                    onChange={e => setSelectedVehicleId(e.target.value)}
                    className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white font-medium text-slate-700 focus:outline-none"
                    required
                  >
                    <option value="">Select Fleet Vehicle</option>
                    {vehicles.map(v => (
                      <option key={v.id} value={v.id}>{v.number} - {v.type}</option>
                    ))}
                  </select>
                </div>

                {/* Transporter Name */}
                <div>
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Transporter / Logistics Agency</label>
                  <input
                    type="text"
                    className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white font-medium text-slate-700 focus:outline-none"
                    value={transporterName}
                    onChange={e => setTransporterName(e.target.value)}
                  />
                </div>
              </div>

              <div className="grid grid-cols-3 gap-3">
                {/* Transit Mode */}
                <div>
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Transit Mode</label>
                  <select
                    value={mode}
                    onChange={e => setMode(e.target.value as any)}
                    className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white font-medium text-slate-700 focus:outline-none"
                  >
                    <option value="Road">Roadway</option>
                    <option value="Rail">Railway</option>
                    <option value="Air">Air Freight</option>
                    <option value="Ship">Shipping</option>
                  </select>
                </div>

                {/* Travel distance */}
                <div>
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Travel Distance (Kms)</label>
                  <input
                    type="number"
                    className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white font-medium text-slate-700 focus:outline-none"
                    value={distance}
                    onChange={e => setDistance(Math.max(1, Number(e.target.value)))}
                  />
                </div>

                {/* Valid From */}
                <div>
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Valid From</label>
                  <IndianDateInput
                    className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white font-medium text-slate-700 focus:outline-none"
                    value={validFrom}
                    onChange={val => setValidFrom(val)}
                  />
                </div>
              </div>

              {/* Valid Until */}
              <div>
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">Expiration Validity Period *</label>
                <IndianDateInput
                  className="w-full px-3 py-2 border border-slate-200 rounded-lg text-xs bg-white font-medium text-slate-700 focus:outline-none"
                  value={validUntil}
                  onChange={val => setValidUntil(val)}
                  required
                />
              </div>

              {/* Form submit */}
              <div className="flex gap-2 justify-end pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setIsCreateOpen(false)}
                  className="px-4 py-2 border border-slate-200 hover:bg-slate-50 text-slate-600 rounded-lg text-xs font-bold transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg text-xs font-bold shadow-md shadow-primary-600/10 transition"
                >
                  Record E-Way Bill
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
